#pragma once
/* Test-only SameBoy identity header -- regenerated by CMake at configure time.
 * Do NOT edit by hand. Pin the SameBoy subtree commit before editing. */

#ifndef GB_VERSION
#define GB_VERSION "1.0.3"
#endif

#ifndef GB_COMMIT
/* Full SHA-1 of references/SameBoy HEAD at the last configure run. */
#define GB_COMMIT "213a12ce93d66b105a113debd9396306066a7cfc"
#endif

#ifndef GB_DIRTY
/* Non-empty string if references/SameBoy has uncommitted tracked changes.
 * Empty string means the working tree is clean. */
#define GB_DIRTY ""
#endif

#ifndef GB_COPYRIGHT_YEAR
#define GB_COPYRIGHT_YEAR "2026"
#endif
