// runtime_test_compiler_main.cpp
// Main for runtime_test_compiler — Crystal compiler/IR TUs.
// These include semantic_ir.hpp + crystal_command.hpp (both ~300-alt variants)
// and require /O1 /Zm2000 to compile without hitting MSVC C1060.
// TUs: runtime_test_scripts, _batches, _vm_state, _text_rng, _pcg_vm
// Run: runtime_test_compiler <rom_path>
#include "engine/world/collision.hpp"
#include "crystal/rom/loader.hpp"
#include "crystal/rom/profile.hpp"
#include <iostream>
#include <string>
#include "scripting/runtime_test_shared.hpp"

int  g_tests_passed      = 0;
int  g_tests_failed      = 0;
bool g_current_test_failed = false;
const crystal::RomData*           g_rom     = nullptr;
const crystal::ExtractionProfile* g_profile = nullptr;
std::string g_generated_lua;

void run_test(const char* name, void (*test)()) {
    std::cout << "Running " << name << "... ";
    g_current_test_failed = false;
    try { test();
        if (g_current_test_failed) { std::cout << "FAIL\n"; g_tests_failed++; }
        else { std::cout << "PASS\n"; g_tests_passed++; }
    } catch (const std::exception& e) {
        std::cout << "EXCEPTION: " << e.what() << "\n"; g_tests_failed++;
    }
}

// Forward declarations
void test_active_coroutine_resume_reyield_sets_script_resumed();
void test_active_coroutine_timed_resume_sets_script_resumed();
void test_bank_utils_bank_to_flat_ptr_at_4000();
void test_bank_utils_bank_to_flat_ptr_at_7fff();
void test_bank_utils_bank_to_flat_ptr_in_rom0();
void test_bank_utils_flat_to_bank_nonzero();
void test_bank_utils_flat_to_bank_one();
void test_bank_utils_flat_to_bank_zero();
void test_bank_utils_getstring_lowering_matches_canonical_helper();
void test_bank_utils_local_ptr_to_flat_getstring_nonzero_bank();
void test_bank_utils_local_ptr_to_flat_sdefer_nonzero_bank();
void test_bank_utils_round_trip();
void test_bank_utils_sdefer_lowering_matches_canonical_helper();
void test_batch1_audio_ops_distinct();
void test_batch1_no_crystal_ids_in_ops();
void test_batch1_screen_fade_variants();
void test_batch1_sprite_ops_distinct();
void test_batch1_sync_palettes_variants();
void test_batch10_check_pokerus_invalidates_context();
void test_batch10_checkpoke_invalidates_context();
void test_batch10_checksave_invalidates_context();
void test_batch10_checkwarp_preserves_context();
void test_batch10_getcoins_uses_coins_source();
void test_batch10_getmoney_uses_typed_money_account();
void test_batch10_getnum_uses_scriptvar_source();
void test_batch10_giveegg_invalidates_context();
void test_batch10_givepoke_invalidates_context();
void test_batch10_number_sources_are_distinct();
void test_batch10_pocketisfull_does_not_invalidate_context();
void test_batch10_pocketisfull_emits_notify_not_absorbed();
void test_batch10_show_text_empty_sequence_fails_legality();
void test_batch10_show_text_nonempty_sequence_passes_legality();
void test_batch10_startbattle_invalidates_context();
void test_batch2_59_not_60_60_not_61();
void test_batch2_no_sem_special_for_59_60();
void test_batch2_special_59_waits_sfx();
void test_batch2_special_60_plays_map_music();
void test_batch3_heal_party_egg_pp_unchanged();
void test_batch3_heal_party_egg_skip();
void test_batch3_heal_party_no_script_result();
void test_batch3_heal_party_pp_formula();
void test_batch3_heal_party_pp_restoration();
void test_batch3_no_sem_special_for_27();
void test_batch3_special_27_heals_party();
void test_batch3_special_27_production_lowering();
void test_batch4_balance_overlay_no_script_result();
void test_batch4_balance_overlay_semantic_distinctions();
void test_batch4_no_sem_special_for_79_80_81();
void test_batch4_special_79_production_lowering();
void test_batch4_special_80_production_lowering();
void test_batch4_special_81_production_lowering();
void test_batch5_check_pokerus_script_result();
void test_batch5_gameboy_check_absorption_proof();
void test_batch5_no_sem_special_for_78_102();
void test_batch5_special_102_production_lowering();
void test_batch5_special_144_remains_sem_special();
void test_batch5_special_78_production_lowering();
void test_batch6_absorption_accounting_invariant();
void test_batch6_special_157_no_sem_special();
void test_batch6_special_157_production_absorption();
void test_batch6_unhandled_special_produces_sem_special();
void test_batch7_special_160_branch_equivalence();
void test_batch7_special_160_no_sem_special();
void test_batch7_special_160_not_zero_instructions();
void test_batch7_special_160_overwrites_stale_script_var();
void test_batch7_special_160_production_lowering();
void test_batch8_dst_operations_no_script_result();
void test_batch8_special_163_emits_sem_yesno();
void test_batch8_special_163_no_sem_special();
void test_batch8_special_163_yesorno_equivalence();
void test_batch8_special_166_167_differ_by_enabled();
void test_batch8_special_166_167_no_sem_special();
void test_batch8_special_166_emits_dst_true();
void test_batch8_special_167_emits_dst_false();
void test_batch9_setval_establishes_context();
void test_batch9_special_152_all_source_valid_selectors_accepted();
void test_batch9_special_152_invalid_encoding_rejected();
void test_batch9_special_152_palette_normalization();
void test_batch9_special_40_no_context_fallback();
void test_batch9_special_40_with_context();
void test_batch9_species_domain_from_profile_not_hardcoded();
void test_behavior_known_unimplemented_errors_explicitly();
void test_behavior_sdefer_routes_to_scheduler();
void test_behavior_unknown_unregistered_errors_explicitly();
void test_behavior_writes_script_var_errors_before_branch();
void test_bg_event_conditional_script_decode();
void test_bg_event_directional_types_preserved();
void test_bg_event_hidden_item_semantic_decode();
void test_capability_face_actor_player_updates_player_facing();
void test_capability_face_actor_updates_npc_facing();
void test_capability_face_player_updates_npc_facing_toward_player();
void test_capability_set_last_talked_records_id();
void test_capability_set_scene_persists_in_game_state();
void test_capability_show_hide_npc_updates_npc_state();
void test_capability_state_var_persists_in_game_state();
void test_capability_teleport_npc_updates_npc_position();
void test_compat_exact_hash_gives_exacthash_match();
void test_compat_incompatible_profile_fails_explicitly();
void test_compat_modified_hash_layout_valid_not_rejected();
void test_coord_event_field_decode();
void test_coord_event_scripts_in_corpus();
void test_corpus_battletowertext_distinct_from_normal_trainer_text();
void test_corpus_battletowertext_no_sem_special();
void test_corpus_battletowertext_produces_trainer_text();
void test_corpus_callasm_0x9f5cb_produces_read_state_var();
void test_corpus_callasm_nearby_addresses_rejected();
void test_corpus_readmem_0xcf64_produces_read_state_var();
void test_corpus_readmem_nearby_addresses_rejected();
void test_cry_and_pokepic_same_source_semantics();
void test_cry_literal_species();
void test_cry_script_var_distinct_from_literal();
void test_cry_zero_dynamic_species();
void test_daycare_species_252_save_load_accepted();
void test_decoder_unique_command_identity_cfg_integrity();
void test_decoder_unique_command_identity_loop();
void test_decoder_unique_command_identity_semantic_ir();
void test_emitter_callstd_no_crash();
void test_emitter_jumpstd_no_crash();
void test_emitter_special_no_crash();
void test_emitter_warp_to_spawn_has_binding();
void test_event_script_id_canonical_format_bg();
void test_event_script_id_canonical_format_coord();
void test_event_script_id_canonical_format_npc();
void test_event_script_id_missing_fails_explicitly();
void test_event_script_id_no_local_positional_survives();
void test_f1_turnobject_direction_preserved_right();
void test_f1_turnobject_direction_preserved_up();
void test_f2_text_ram_op_preserved_not_dropped();
void test_f3_givepoke_held_item_preserved();
void test_f3_no_second_player_authority();
void test_f3_player_authority_warp_uses_latest_position();
void test_f4_failed_prepare_connection_leaves_everything_unchanged();
void test_f4_failed_prepare_warp_leaves_everything_unchanged();
void test_f4_prepare_warp_does_not_mutate_player();
void test_f4_scripted_warp_coordinates_preserved();
void test_f4_transition_failure_leaves_old_world_coherent();
void test_f4_transition_staged_world_state_separate();
void test_f5_save_v2_npc_section_mandatory_truncations();
void test_f6_canonical_rng_not_reset_on_map_transition();
void test_f6_simultaneous_wakeup_deterministic_order();
void test_f7_save_invalid_direction_rejected();
void test_f7_text_sequence_ordered_consumption();
void test_f8_money_account_player_vs_mom();
void test_fidelity11_askforphonenumber_distinct_from_addphonenumber();
void test_fidelity11_catchtutorial_distinct_from_startbattle();
void test_fidelity11_catchtutorial_preserves_type_byte();
void test_fidelity11_deactivatefacing_distinct_from_pause();
void test_fidelity11_endall_distinct_from_end();
void test_fidelity11_getname_type1_pokemon();
void test_fidelity11_getname_type2_move();
void test_fidelity11_getname_type3_dummy_not_item();
void test_fidelity11_getname_type4_item_not_trainer();
void test_fidelity11_getname_type5_partyot();
void test_fidelity11_getname_type7_trainer();
void test_fidelity11_invalid_domain_gates_linker();
void test_fidelity11_jumptext_distinct_from_writetext();
void test_fidelity11_jumptextfaceplayer_preserves_text();
void test_fidelity11_loadmenu_preserves_header_pointer();
void test_fidelity11_promptbutton_distinct_from_waitbutton();
void test_fidelity11_verbosegiveitemvar_variable_semantics();
void test_fidelity11_verticalmenu_distinct_from_2dmenu();
void test_fidelity11_writetext_distinct_pointers_distinct_sequences();
void test_field_context_activate_consumes_actor();
void test_field_context_clear_context_clears_all();
void test_field_context_encounter_failure_clears_encounter();
void test_field_context_encounter_success_establishes_encounter();
void test_field_context_full_rock_smash_encounter_flow();
void test_field_context_full_strength_flow();
void test_field_context_load_encounter_consumes_encounter();
void test_field_context_new_runtime_starts_clean();
void test_field_context_no_encounter_no_stale_state();
void test_field_context_prepare_nickname_preserves_actor();
void test_field_context_read_species_preserves_encounter();
void test_field_context_rock_smash_available_establishes_actor();
void test_field_context_rock_smash_unavailable_clears_actor();
void test_field_context_runtime_isolation_actor();
void test_field_context_runtime_isolation_encounter();
void test_field_context_strength_active_persists_across_scripts();
void test_field_context_strength_already_active_clears_actor();
void test_field_context_strength_available_establishes_actor();
void test_field_context_strength_unavailable_clears_actor();
void test_field_context_user_declines_flow();
void test_flag_api_stub_isolation();
void test_gamestate_deserialize_malformed_rejects();
void test_icon_format_128_bytes_total();
void test_icon_format_16x16_geometry();
void test_icon_format_bigmon_packaged_via_closure();
void test_icon_format_pikachu_pixel_hash();
void test_input_edge_held_across_multiple_ticks();
void test_input_edge_multiple_render_frames_preserves_press();
void test_input_edge_new_press_after_release();
void test_input_edge_one_press_four_ticks_consumed_once();
void test_input_edge_one_press_one_tick_consumed_once();
void test_input_edge_press_release_before_tick();
void test_input_edge_release_consumed_once();
void test_input_edge_zero_tick_frame_preserves_press();
void test_input_edge_zero_tick_frame_preserves_release();
void test_input_snapshot_direction_helper();
void test_input_system_arrow_bindings();
void test_input_system_default_bindings();
void test_input_system_gamepad_bindings();
void test_input_system_get_action_interact();
void test_input_system_get_action_movement();
void test_input_system_key_events();
void test_input_system_latch();
void test_input_system_rebind();
void test_lua_coroutine_cleanup_via_resume();
void test_lua_coroutine_cleanup_via_resume_with_result();
void test_movement_callback_wires_to_live_object();
void test_movement_no_terminator_throws();
void test_movement_valid_terminates_correctly();
void test_multipage_rival_script_three_segments();
void test_multipage_text_stream_encoding();
void test_multipage_text_with_cont_preserves_scroll_line();
void test_multipage_text_with_para_advances_all_pages();
void test_native_text_from_runtime_decimal_preserves_operands();
void test_native_text_from_runtime_no_silent_blank_fallthrough();
void test_native_text_from_runtime_ram_preserves_operands();
void test_native_text_from_runtime_unsupported_throws();
void test_newbark_npc_behaviors_extracted();
void test_no_second_authoritative_rng_stream();
void test_npc_collision_with_player();
void test_npc_destination_occupancy_blocks_conflicting_movement();
void test_npc_frozen_blocks_movement();
void test_npc_idle_timer_countdown();
void test_npc_movement_behavior_conversion();
void test_npc_movement_facing_conversion();
void test_npc_respects_radius_bounds();
void test_npc_rng_determinism_via_gamestate();
void test_npc_rng_save_restore_determinism();
void test_npc_spin_changes_facing();
void test_npc_standing_never_moves();
void test_npc_walk_changes_position();
void test_npc_walk_up_down_direction();
void test_object_event_palette_type_decode();
void test_package_context_isolation();
void test_pcg_bounded_one_always_zero();
void test_pcg_bounded_representative_value();
void test_pcg_bounded_zero_throws_no_draw();
void test_pcg_dv_draw_count_two_semantic();
void test_pcg_known_sequence_seed_deadbeef();
void test_pcg_map_transition_does_not_perturb_canonical();
void test_pcg_next_u64_hi_lo_ordering();
void test_pcg_next_u8_draw_count();
void test_pcg_npc_movement_uses_canonical_rng();
void test_pcg_npc_save_load_canonical_continuation();
void test_pcg_presentation_rng_does_not_perturb_canonical();
void test_pcg_save_load_exact_continuation();
void test_pcg_seed_zero_known_state();
void test_pcg_v4_migration_deterministic();
void test_pcg_v5_save_roundtrip();
void test_pokepic_literal_species();
void test_pokepic_zero_dynamic_species();
void test_presentation_hook_isolation();
void test_random_chance_correct_probability_contract();
void test_random_chance_invalid_percent_throws();
void test_renderer_staged_prepare_isolates_cross_operation_failure();
void test_renderer_staged_prepare_worldstate_unchanged_on_load_failure();
void test_reset_after_script_completed();
void test_reset_cancels_active_coroutine_no_timed_resume();
void test_reset_when_no_script_active();
void test_reset_when_script_yielded();
void test_scheduler_2_second_hitch_retains_debt();
void test_scheduler_500ms_hitch_retains_debt();
void test_scheduler_interpolation_alpha_clamped();
void test_scheduler_repeated_updates_catch_up();
void test_scheduler_total_ticks_equals_elapsed_time();
void test_script_errors_after_resume_sets_error();
void test_script_errors_immediately_returns_false();
void test_script_finishes_normally_sets_complete();
void test_script_resumed_no_resume_attempt();
void test_script_resumed_yielded_to_completed();
void test_script_resumed_yielded_to_yielded();
void test_script_runtime_error_during_start_returns_false();
void test_script_state_checkcellnum_invalidates();
void test_script_state_checkphonecall_invalidates();
void test_script_state_checktime_invalidates();
void test_script_state_checkver_establishes_context();
void test_script_state_cry_and_pokepic_same_source_semantics();
void test_script_state_cry_nonzero_is_literal();
void test_script_state_cry_zero_is_script_var_not_literal();
void test_script_state_delcmdqueue_invalidates();
void test_script_state_pokepic_nonzero_is_literal();
void test_script_state_pokepic_zero_is_script_var_not_literal();
void test_script_state_setval_preserved_across_noop_command();
void test_script_state_setval_yesorno_invalidates_context();
void test_script_state_verbosegiveitemvar_invalidates();
void test_script_var_propagates_across_non_writer();
void test_scripted_movement_async_auto_enabled_by_set_lua_runtime();
void test_scripted_movement_destructor_clears_stale_manager_pointer();
void test_scripted_movement_e2e_command_order_preserved();
void test_scripted_movement_e2e_coroutine_resumes_only_after_completion();
void test_scripted_movement_e2e_nonzero_npc_not_player();
void test_scripted_movement_e2e_npc_steps_left_position_commits();
void test_scripted_movement_e2e_turn_changes_facing_not_position();
void test_scripted_movement_e2e_two_actors_no_alias();
void test_scripted_movement_malformed_payload_fails_explicitly();
void test_scripted_movement_rebind_clears_old_wires_new();
void test_sem_game_specific_event_behavior_name_is_source_proven_not_raw_id();
void test_sem_game_specific_event_no_write_preserves_context();
void test_sem_game_specific_event_writes_var_flag_blocks_constant_propagation();
void test_sem_special_clean_ir_still_passes_legality();
void test_sem_special_rejected_by_stage5_legality_gate();
// test_sem_special_still_rejected_after_registry_cleanup migrated to legality_gate_test.cpp
void test_semantic_fix_encountermusic_distinct_from_playmapmusic();
void test_semantic_fix_getmoney_preserves_account();
void test_semantic_fix_getstring_preserves_text_pointer();
void test_semantic_fix_gettrainername_preserves_both_operands();
void test_semantic_fix_newloadmap_preserves_method();
void test_semantic_fix_reanchormap_distinct_from_refreshmap();
void test_semantic_fix_refreshmap_distinct_from_reanchormap();
void test_semantic_fix_sdefer_bank_resolution();
void test_semantic_fix_text_identity_distinguishes_controls();
void test_semantic_fix_text_identity_distinguishes_ram_addresses();
void test_species_finder_bulbasaur_record_correct();
void test_species_finder_last_record_is_mew();
void test_species_finder_non251_profile_same_path();
void test_species_finder_stock_count_is_251();
void test_species_finder_truncated_base_data_fails();
void test_species_icon_map_covers_full_domain();
void test_species_linker_refs_are_exact_resolved();
void test_species_linker_unknown_species_invalid_domain();
void test_stale_script_var_giveitem_invalidates();
void test_stale_script_var_yesorno_invalidates_before_map_radio();
void test_text_arg_slot_numbering_table_driven();
void test_text_arg_slot_wplayername_hard_fails();
void test_text_battle_nickname_is_ram_source_not_arg();
void test_text_enemy_nickname_is_ram_source_not_arg();
void test_text_literal_at_returns_to_outer_stream();
void test_text_literal_tx_opcode_overlap_0x14();
void test_text_prepared_string2_is_ram_source_not_arg();
void test_text_presentation_ops_dropped_not_failed();
void test_text_ram_source_domain_distinct_from_arg_domain();
void test_text_resource_can_begin_with_dynamic_command();
void test_text_string_buffer_id0_maps_to_arg_slot0();
void test_text_string_buffer_id4_maps_to_arg_slot4();
void test_text_string_buffer_id6_maps_to_arg_slot6();
void test_text_string_buffer_invalid_id255_hard_fails();
void test_text_string_buffer_invalid_id7_hard_fails();
void test_text_tx_bcd_hard_fails();
void test_text_tx_day_produces_day_op();
void test_text_tx_decimal_unknown_address_hard_fails();
void test_text_tx_decimal_wscriptvar_produces_script_var_decimal();
void test_text_tx_far_inlines_referenced_text();
void test_text_tx_far_without_registry_hard_fails();
void test_text_tx_pause_frame_count_preserved_explicitly();
void test_text_tx_pause_produces_pause_with_30_frames();
void test_text_tx_prompt_button_produces_inline_prompt_button_not_dropped();
void test_text_tx_prompt_button_standalone_produces_single_element();
void test_text_tx_ram_unknown_address_hard_fails();
void test_text_tx_ram_wstringbuffer3_maps_to_arg_slot0();
void test_text_tx_ram_wstringbuffer4_maps_to_arg_slot1();
void test_text_tx_ram_wstringbuffer5_maps_to_arg_slot2();
void test_text_tx_raw_unknown_opcode_hard_fails();
void test_text_tx_sound_fanfare_produces_typed_sound_kind();
void test_text_tx_sound_item_produces_typed_sound_kind();
void test_textraw_empty_raw_handled();
void test_textraw_identity_distinguishes_contents();
void test_textraw_identity_identical_contents_match();
void test_timing_144hz_rendering_produces_same_ticks();
void test_timing_60hz_rendering_produces_consistent_ticks();
void test_timing_equivalent_elapsed_same_tick_count();
void test_timing_irregular_frames_same_result();
void test_timing_scheduler_advance();
void test_timing_scheduler_basic();
void test_tx_box_height_width_semantics();
void test_tx_far_dedup_different_bank_gets_different_id();
void test_tx_far_identity_distinguishes_address();
void test_tx_far_identity_distinguishes_bank();
void test_unrelated_coroutine_resume_does_not_set_script_resumed();
void test_vm_call_returns_to_continuation();
void test_vm_callee_end_does_not_exit_top_level();
void test_vm_deferred_failure_propagates_error();
void test_vm_endall_inside_nested_call_terminates();
void test_vm_nested_calls_unwind_correctly();
void test_vm_result_nonzero_integer_true();
void test_vm_result_one_takes_true_branch();
void test_vm_result_zero_takes_false_branch();
void test_vm_sdefer_cleared_on_loop_destroy();
void test_vm_sdefer_cleared_on_rebind();
void test_vm_setvar_from_result_zero_stores_zero();
void test_wait_frames_before_expiry_no_resume();
void test_wait_frames_expiry_reyield_sets_resumed();
void test_wait_frames_expiry_sets_resumed();
void test_wait_seconds_not_immediate_resume();
void test_wait_seconds_precision_0_05s_is_3_ticks();
void test_wait_seconds_precision_0_1s_is_6_ticks();
void test_wait_seconds_precision_1_0s_is_60_ticks();
void test_wait_seconds_resume_sets_flag();
void test_wait_seconds_resumes_after_duration();
void test_wait_seconds_zero_duration();
void test_world_api_stub_isolation();
void test_writecmdqueue_same_ptr_different_banks_distinct();
void test_yielded_script_remains_nonterminal();

int main(int argc, char* argv[]) {
    if (argc < 2) { std::cerr << "Usage: " << argv[0] << " <rom_path>\n"; return 1; }
    auto rom = crystal::RomData::load(argv[1]);
    if (!rom) { std::cerr << "Failed to load ROM\n"; return 1; }
    auto& registry = crystal::ProfileRegistry::instance();
    auto profile = registry.get_profile_by_hash(rom->hash());
    if (!profile) { std::cerr << "ROM not supported\n"; return 1; }
    g_rom = rom.get(); g_profile = profile;
    std::cout << "\n=== Runtime Tests (compiler) ===\n\n";

    RUN_TEST(gamestate_deserialize_malformed_rejects);
    RUN_TEST(f3_player_authority_warp_uses_latest_position);
    RUN_TEST(f4_transition_failure_leaves_old_world_coherent);
    RUN_TEST(f4_transition_staged_world_state_separate);
    RUN_TEST(renderer_staged_prepare_worldstate_unchanged_on_load_failure);
    RUN_TEST(renderer_staged_prepare_isolates_cross_operation_failure);
    RUN_TEST(f3_no_second_player_authority);
    RUN_TEST(f4_prepare_warp_does_not_mutate_player);
    RUN_TEST(f4_failed_prepare_warp_leaves_everything_unchanged);
    RUN_TEST(f4_failed_prepare_connection_leaves_everything_unchanged);
    RUN_TEST(f5_save_v2_npc_section_mandatory_truncations);
    RUN_TEST(f6_simultaneous_wakeup_deterministic_order);
    RUN_TEST(f7_text_sequence_ordered_consumption);
    RUN_TEST(scheduler_interpolation_alpha_clamped);
    RUN_TEST(multipage_text_stream_encoding);
    RUN_TEST(multipage_text_with_para_advances_all_pages);
    RUN_TEST(multipage_text_with_cont_preserves_scroll_line);
    RUN_TEST(multipage_rival_script_three_segments);
    RUN_TEST(input_system_default_bindings);
    RUN_TEST(input_system_arrow_bindings);
    RUN_TEST(input_system_gamepad_bindings);
    RUN_TEST(input_system_key_events);
    RUN_TEST(input_system_get_action_movement);
    RUN_TEST(input_system_get_action_interact);
    RUN_TEST(input_system_rebind);
    RUN_TEST(input_system_latch);
    RUN_TEST(input_snapshot_direction_helper);
    RUN_TEST(npc_movement_behavior_conversion);
    RUN_TEST(npc_movement_facing_conversion);
    RUN_TEST(npc_idle_timer_countdown);
    RUN_TEST(npc_frozen_blocks_movement);
    RUN_TEST(npc_standing_never_moves);
    RUN_TEST(npc_spin_changes_facing);
    RUN_TEST(npc_walk_changes_position);
    RUN_TEST(npc_respects_radius_bounds);
    RUN_TEST(npc_collision_with_player);
    RUN_TEST(npc_walk_up_down_direction);
    RUN_TEST(newbark_npc_behaviors_extracted);
    RUN_TEST(npc_rng_determinism_via_gamestate);
    RUN_TEST(npc_rng_save_restore_determinism);
    RUN_TEST(scripted_movement_e2e_npc_steps_left_position_commits);
    RUN_TEST(scripted_movement_e2e_turn_changes_facing_not_position);
    RUN_TEST(scripted_movement_e2e_coroutine_resumes_only_after_completion);
    RUN_TEST(scripted_movement_e2e_nonzero_npc_not_player);
    RUN_TEST(scripted_movement_e2e_two_actors_no_alias);
    RUN_TEST(scripted_movement_malformed_payload_fails_explicitly);
    RUN_TEST(scripted_movement_destructor_clears_stale_manager_pointer);
    RUN_TEST(scripted_movement_rebind_clears_old_wires_new);
    RUN_TEST(scripted_movement_async_auto_enabled_by_set_lua_runtime);
    RUN_TEST(scripted_movement_e2e_command_order_preserved);
    RUN_TEST(field_context_strength_available_establishes_actor);
    RUN_TEST(field_context_strength_unavailable_clears_actor);
    RUN_TEST(field_context_strength_already_active_clears_actor);
    RUN_TEST(field_context_activate_consumes_actor);
    RUN_TEST(field_context_rock_smash_available_establishes_actor);
    RUN_TEST(field_context_rock_smash_unavailable_clears_actor);
    RUN_TEST(field_context_encounter_success_establishes_encounter);
    RUN_TEST(field_context_encounter_failure_clears_encounter);
    RUN_TEST(field_context_load_encounter_consumes_encounter);
    RUN_TEST(field_context_read_species_preserves_encounter);
    RUN_TEST(field_context_prepare_nickname_preserves_actor);
    RUN_TEST(field_context_clear_context_clears_all);
    RUN_TEST(field_context_user_declines_flow);
    RUN_TEST(field_context_no_encounter_no_stale_state);
    RUN_TEST(field_context_full_strength_flow);
    RUN_TEST(field_context_full_rock_smash_encounter_flow);
    RUN_TEST(field_context_new_runtime_starts_clean);
    RUN_TEST(field_context_runtime_isolation_actor);
    RUN_TEST(field_context_runtime_isolation_encounter);
    RUN_TEST(world_api_stub_isolation);
    RUN_TEST(flag_api_stub_isolation);
    RUN_TEST(package_context_isolation);
    RUN_TEST(presentation_hook_isolation);
    RUN_TEST(field_context_strength_active_persists_across_scripts);
    RUN_TEST(batch1_screen_fade_variants);
    RUN_TEST(batch1_sync_palettes_variants);
    RUN_TEST(batch1_sprite_ops_distinct);
    RUN_TEST(batch1_audio_ops_distinct);
    RUN_TEST(batch1_no_crystal_ids_in_ops);
    RUN_TEST(batch2_special_59_waits_sfx);
    RUN_TEST(batch2_special_60_plays_map_music);
    RUN_TEST(batch2_no_sem_special_for_59_60);
    RUN_TEST(batch2_59_not_60_60_not_61);
    RUN_TEST(batch3_special_27_heals_party);
    RUN_TEST(batch3_no_sem_special_for_27);
    RUN_TEST(batch3_heal_party_pp_formula);
    RUN_TEST(batch3_heal_party_egg_skip);
    RUN_TEST(batch3_heal_party_no_script_result);
    RUN_TEST(batch3_special_27_production_lowering);
    RUN_TEST(batch3_heal_party_pp_restoration);
    RUN_TEST(batch3_heal_party_egg_pp_unchanged);
    RUN_TEST(batch4_special_79_production_lowering);
    RUN_TEST(batch4_special_80_production_lowering);
    RUN_TEST(batch4_special_81_production_lowering);
    RUN_TEST(batch4_balance_overlay_semantic_distinctions);
    RUN_TEST(batch4_no_sem_special_for_79_80_81);
    RUN_TEST(batch4_balance_overlay_no_script_result);
    RUN_TEST(batch5_special_78_production_lowering);
    RUN_TEST(batch5_special_102_production_lowering);
    RUN_TEST(batch5_special_144_remains_sem_special);
    RUN_TEST(batch5_no_sem_special_for_78_102);
    RUN_TEST(batch5_gameboy_check_absorption_proof);
    RUN_TEST(batch5_check_pokerus_script_result);
    RUN_TEST(batch6_special_157_production_absorption);
    RUN_TEST(batch6_special_157_no_sem_special);
    RUN_TEST(batch6_unhandled_special_produces_sem_special);
    RUN_TEST(batch6_absorption_accounting_invariant);
    RUN_TEST(batch7_special_160_production_lowering);
    RUN_TEST(batch7_special_160_no_sem_special);
    RUN_TEST(batch7_special_160_not_zero_instructions);
    RUN_TEST(batch7_special_160_overwrites_stale_script_var);
    RUN_TEST(batch7_special_160_branch_equivalence);
    RUN_TEST(corpus_battletowertext_produces_trainer_text);
    RUN_TEST(corpus_battletowertext_no_sem_special);
    RUN_TEST(corpus_battletowertext_distinct_from_normal_trainer_text);
    RUN_TEST(corpus_readmem_0xcf64_produces_read_state_var);
    RUN_TEST(corpus_readmem_nearby_addresses_rejected);
    RUN_TEST(corpus_callasm_0x9f5cb_produces_read_state_var);
    RUN_TEST(corpus_callasm_nearby_addresses_rejected);
    RUN_TEST(batch8_special_163_emits_sem_yesno);
    RUN_TEST(batch8_special_163_no_sem_special);
    RUN_TEST(batch8_special_163_yesorno_equivalence);
    RUN_TEST(batch8_special_166_emits_dst_true);
    RUN_TEST(batch8_special_167_emits_dst_false);
    RUN_TEST(batch8_special_166_167_differ_by_enabled);
    RUN_TEST(batch8_special_166_167_no_sem_special);
    RUN_TEST(batch8_dst_operations_no_script_result);
    RUN_TEST(batch9_setval_establishes_context);
    RUN_TEST(batch9_special_40_with_context);
    RUN_TEST(batch9_special_40_no_context_fallback);
    RUN_TEST(batch9_special_152_palette_normalization);
    RUN_TEST(batch9_special_152_invalid_encoding_rejected);
    RUN_TEST(batch9_special_152_all_source_valid_selectors_accepted);
    RUN_TEST(batch9_species_domain_from_profile_not_hardcoded);
    RUN_TEST(decoder_unique_command_identity_loop);
    RUN_TEST(decoder_unique_command_identity_cfg_integrity);
    RUN_TEST(decoder_unique_command_identity_semantic_ir);
    RUN_TEST(timing_scheduler_basic);
    RUN_TEST(timing_scheduler_advance);
    RUN_TEST(timing_60hz_rendering_produces_consistent_ticks);
    RUN_TEST(timing_144hz_rendering_produces_same_ticks);
    RUN_TEST(timing_irregular_frames_same_result);
    RUN_TEST(timing_equivalent_elapsed_same_tick_count);
    RUN_TEST(input_edge_one_press_one_tick_consumed_once);
    RUN_TEST(input_edge_one_press_four_ticks_consumed_once);
    RUN_TEST(input_edge_held_across_multiple_ticks);
    RUN_TEST(input_edge_release_consumed_once);
    RUN_TEST(input_edge_zero_tick_frame_preserves_press);
    RUN_TEST(input_edge_zero_tick_frame_preserves_release);
    RUN_TEST(input_edge_press_release_before_tick);
    RUN_TEST(input_edge_new_press_after_release);
    RUN_TEST(input_edge_multiple_render_frames_preserves_press);
    RUN_TEST(scheduler_500ms_hitch_retains_debt);
    RUN_TEST(scheduler_2_second_hitch_retains_debt);
    RUN_TEST(scheduler_repeated_updates_catch_up);
    RUN_TEST(scheduler_total_ticks_equals_elapsed_time);
    RUN_TEST(lua_coroutine_cleanup_via_resume);
    RUN_TEST(lua_coroutine_cleanup_via_resume_with_result);
    RUN_TEST(npc_destination_occupancy_blocks_conflicting_movement);
    RUN_TEST(coord_event_field_decode);
    RUN_TEST(bg_event_directional_types_preserved);
    RUN_TEST(bg_event_hidden_item_semantic_decode);
    RUN_TEST(bg_event_conditional_script_decode);
    RUN_TEST(object_event_palette_type_decode);
    RUN_TEST(script_resumed_no_resume_attempt);
    RUN_TEST(script_resumed_yielded_to_completed);
    RUN_TEST(script_resumed_yielded_to_yielded);
    RUN_TEST(wait_frames_before_expiry_no_resume);
    RUN_TEST(movement_callback_wires_to_live_object);
    RUN_TEST(wait_frames_expiry_sets_resumed);
    RUN_TEST(wait_frames_expiry_reyield_sets_resumed);
    RUN_TEST(wait_seconds_not_immediate_resume);
    RUN_TEST(wait_seconds_resumes_after_duration);
    RUN_TEST(wait_seconds_resume_sets_flag);
    RUN_TEST(wait_seconds_zero_duration);
    RUN_TEST(wait_seconds_precision_0_05s_is_3_ticks);
    RUN_TEST(wait_seconds_precision_0_1s_is_6_ticks);
    RUN_TEST(wait_seconds_precision_1_0s_is_60_ticks);
    RUN_TEST(unrelated_coroutine_resume_does_not_set_script_resumed);
    RUN_TEST(active_coroutine_timed_resume_sets_script_resumed);
    RUN_TEST(active_coroutine_resume_reyield_sets_script_resumed);
    RUN_TEST(script_finishes_normally_sets_complete);
    RUN_TEST(script_errors_after_resume_sets_error);
    RUN_TEST(script_errors_immediately_returns_false);
    RUN_TEST(script_runtime_error_during_start_returns_false);
    RUN_TEST(yielded_script_remains_nonterminal);
    RUN_TEST(reset_cancels_active_coroutine_no_timed_resume);
    RUN_TEST(reset_when_no_script_active);
    RUN_TEST(reset_after_script_completed);
    RUN_TEST(reset_when_script_yielded);
    RUN_TEST(coord_event_scripts_in_corpus);
    RUN_TEST(stale_script_var_yesorno_invalidates_before_map_radio);
    RUN_TEST(script_var_propagates_across_non_writer);
    RUN_TEST(stale_script_var_giveitem_invalidates);
    RUN_TEST(cry_literal_species);
    RUN_TEST(cry_zero_dynamic_species);
    RUN_TEST(cry_script_var_distinct_from_literal);
    RUN_TEST(pokepic_literal_species);
    RUN_TEST(pokepic_zero_dynamic_species);
    RUN_TEST(cry_and_pokepic_same_source_semantics);
    RUN_TEST(writecmdqueue_same_ptr_different_banks_distinct);
    RUN_TEST(movement_valid_terminates_correctly);
    RUN_TEST(movement_no_terminator_throws);
    RUN_TEST(script_state_setval_yesorno_invalidates_context);
    RUN_TEST(script_state_setval_preserved_across_noop_command);
    RUN_TEST(script_state_cry_zero_is_script_var_not_literal);
    RUN_TEST(script_state_cry_nonzero_is_literal);
    RUN_TEST(script_state_pokepic_zero_is_script_var_not_literal);
    RUN_TEST(script_state_pokepic_nonzero_is_literal);
    RUN_TEST(script_state_cry_and_pokepic_same_source_semantics);
    RUN_TEST(script_state_verbosegiveitemvar_invalidates);
    RUN_TEST(script_state_checkcellnum_invalidates);
    RUN_TEST(script_state_delcmdqueue_invalidates);
    RUN_TEST(script_state_checkphonecall_invalidates);
    RUN_TEST(script_state_checktime_invalidates);
    RUN_TEST(script_state_checkver_establishes_context);
    RUN_TEST(text_literal_tx_opcode_overlap_0x14);
    RUN_TEST(text_literal_at_returns_to_outer_stream);
    RUN_TEST(text_resource_can_begin_with_dynamic_command);
    RUN_TEST(tx_box_height_width_semantics);
    RUN_TEST(tx_far_identity_distinguishes_bank);
    RUN_TEST(tx_far_identity_distinguishes_address);
    RUN_TEST(tx_far_dedup_different_bank_gets_different_id);
    RUN_TEST(textraw_identity_distinguishes_contents);
    RUN_TEST(textraw_identity_identical_contents_match);
    RUN_TEST(textraw_empty_raw_handled);
    RUN_TEST(bank_utils_flat_to_bank_zero);
    RUN_TEST(bank_utils_flat_to_bank_one);
    RUN_TEST(bank_utils_flat_to_bank_nonzero);
    RUN_TEST(bank_utils_bank_to_flat_ptr_at_4000);
    RUN_TEST(bank_utils_bank_to_flat_ptr_at_7fff);
    RUN_TEST(bank_utils_bank_to_flat_ptr_in_rom0);
    RUN_TEST(bank_utils_round_trip);
    RUN_TEST(bank_utils_local_ptr_to_flat_sdefer_nonzero_bank);
    RUN_TEST(bank_utils_local_ptr_to_flat_getstring_nonzero_bank);
    RUN_TEST(bank_utils_sdefer_lowering_matches_canonical_helper);
    RUN_TEST(bank_utils_getstring_lowering_matches_canonical_helper);
    RUN_TEST(semantic_fix_gettrainername_preserves_both_operands);
    RUN_TEST(semantic_fix_getstring_preserves_text_pointer);
    RUN_TEST(semantic_fix_getmoney_preserves_account);
    RUN_TEST(semantic_fix_encountermusic_distinct_from_playmapmusic);
    RUN_TEST(semantic_fix_newloadmap_preserves_method);
    RUN_TEST(semantic_fix_reanchormap_distinct_from_refreshmap);
    RUN_TEST(semantic_fix_refreshmap_distinct_from_reanchormap);
    RUN_TEST(semantic_fix_sdefer_bank_resolution);
    RUN_TEST(semantic_fix_text_identity_distinguishes_controls);
    RUN_TEST(semantic_fix_text_identity_distinguishes_ram_addresses);
    RUN_TEST(text_string_buffer_id4_maps_to_arg_slot4);
    RUN_TEST(text_string_buffer_id0_maps_to_arg_slot0);
    RUN_TEST(text_string_buffer_id6_maps_to_arg_slot6);
    RUN_TEST(text_string_buffer_invalid_id7_hard_fails);
    RUN_TEST(text_string_buffer_invalid_id255_hard_fails);
    RUN_TEST(text_tx_ram_wstringbuffer3_maps_to_arg_slot0);
    RUN_TEST(text_tx_ram_wstringbuffer4_maps_to_arg_slot1);
    RUN_TEST(text_tx_ram_wstringbuffer5_maps_to_arg_slot2);
    RUN_TEST(text_tx_ram_unknown_address_hard_fails);
    RUN_TEST(text_tx_bcd_hard_fails);
    RUN_TEST(text_tx_decimal_wscriptvar_produces_script_var_decimal);
    RUN_TEST(text_tx_decimal_unknown_address_hard_fails);
    RUN_TEST(text_tx_far_inlines_referenced_text);
    RUN_TEST(text_tx_far_without_registry_hard_fails);
    RUN_TEST(text_tx_day_produces_day_op);
    RUN_TEST(text_tx_sound_item_produces_typed_sound_kind);
    RUN_TEST(text_tx_sound_fanfare_produces_typed_sound_kind);
    RUN_TEST(text_presentation_ops_dropped_not_failed);
    RUN_TEST(text_tx_raw_unknown_opcode_hard_fails);
    RUN_TEST(text_arg_slot_numbering_table_driven);
    RUN_TEST(text_ram_source_domain_distinct_from_arg_domain);
    RUN_TEST(text_arg_slot_wplayername_hard_fails);
    RUN_TEST(text_tx_prompt_button_produces_inline_prompt_button_not_dropped);
    RUN_TEST(text_tx_prompt_button_standalone_produces_single_element);
    RUN_TEST(text_tx_pause_produces_pause_with_30_frames);
    RUN_TEST(text_tx_pause_frame_count_preserved_explicitly);
    RUN_TEST(text_enemy_nickname_is_ram_source_not_arg);
    RUN_TEST(text_battle_nickname_is_ram_source_not_arg);
    RUN_TEST(text_prepared_string2_is_ram_source_not_arg);
    RUN_TEST(sem_game_specific_event_writes_var_flag_blocks_constant_propagation);
    RUN_TEST(sem_game_specific_event_no_write_preserves_context);
    RUN_TEST(sem_game_specific_event_behavior_name_is_source_proven_not_raw_id);
    RUN_TEST(fidelity11_writetext_distinct_pointers_distinct_sequences);
    RUN_TEST(fidelity11_jumptext_distinct_from_writetext);
    RUN_TEST(fidelity11_jumptextfaceplayer_preserves_text);
    RUN_TEST(fidelity11_endall_distinct_from_end);
    RUN_TEST(fidelity11_catchtutorial_distinct_from_startbattle);
    RUN_TEST(fidelity11_catchtutorial_preserves_type_byte);
    RUN_TEST(fidelity11_loadmenu_preserves_header_pointer);
    RUN_TEST(fidelity11_verticalmenu_distinct_from_2dmenu);
    RUN_TEST(fidelity11_deactivatefacing_distinct_from_pause);
    RUN_TEST(fidelity11_verbosegiveitemvar_variable_semantics);
    RUN_TEST(fidelity11_askforphonenumber_distinct_from_addphonenumber);
    RUN_TEST(fidelity11_promptbutton_distinct_from_waitbutton);
    RUN_TEST(fidelity11_getname_type1_pokemon);
    RUN_TEST(fidelity11_getname_type2_move);
    RUN_TEST(fidelity11_getname_type3_dummy_not_item);
    RUN_TEST(fidelity11_getname_type4_item_not_trainer);
    RUN_TEST(fidelity11_getname_type5_partyot);
    RUN_TEST(fidelity11_getname_type7_trainer);
    RUN_TEST(fidelity11_invalid_domain_gates_linker);
    RUN_TEST(batch10_checksave_invalidates_context);
    RUN_TEST(batch10_startbattle_invalidates_context);
    RUN_TEST(batch10_checkpoke_invalidates_context);
    RUN_TEST(batch10_givepoke_invalidates_context);
    RUN_TEST(batch10_giveegg_invalidates_context);
    RUN_TEST(batch10_check_pokerus_invalidates_context);
    RUN_TEST(batch10_checkwarp_preserves_context);
    RUN_TEST(batch10_pocketisfull_emits_notify_not_absorbed);
    RUN_TEST(batch10_pocketisfull_does_not_invalidate_context);
    RUN_TEST(batch10_show_text_empty_sequence_fails_legality);
    RUN_TEST(batch10_show_text_nonempty_sequence_passes_legality);
    RUN_TEST(batch10_getcoins_uses_coins_source);
    RUN_TEST(batch10_getnum_uses_scriptvar_source);
    RUN_TEST(batch10_getmoney_uses_typed_money_account);
    RUN_TEST(batch10_number_sources_are_distinct);
    RUN_TEST(sem_special_rejected_by_stage5_legality_gate);
    RUN_TEST(sem_special_clean_ir_still_passes_legality);
    RUN_TEST(emitter_jumpstd_no_crash);
    RUN_TEST(emitter_callstd_no_crash);
    RUN_TEST(emitter_special_no_crash);
    RUN_TEST(emitter_warp_to_spawn_has_binding);
    RUN_TEST(f1_turnobject_direction_preserved_right);
    RUN_TEST(f1_turnobject_direction_preserved_up);
    RUN_TEST(f4_scripted_warp_coordinates_preserved);
    RUN_TEST(f3_givepoke_held_item_preserved);
    RUN_TEST(f8_money_account_player_vs_mom);
    RUN_TEST(f2_text_ram_op_preserved_not_dropped);
    RUN_TEST(native_text_from_runtime_ram_preserves_operands);
    RUN_TEST(native_text_from_runtime_decimal_preserves_operands);
    RUN_TEST(native_text_from_runtime_unsupported_throws);
    RUN_TEST(native_text_from_runtime_no_silent_blank_fallthrough);
    RUN_TEST(f6_canonical_rng_not_reset_on_map_transition);
    RUN_TEST(f7_save_invalid_direction_rejected);
    RUN_TEST(icon_format_16x16_geometry);
    RUN_TEST(icon_format_128_bytes_total);
    RUN_TEST(icon_format_pikachu_pixel_hash);
    RUN_TEST(icon_format_bigmon_packaged_via_closure);
    RUN_TEST(pcg_known_sequence_seed_deadbeef);
    RUN_TEST(pcg_next_u8_draw_count);
    RUN_TEST(pcg_next_u64_hi_lo_ordering);
    RUN_TEST(pcg_seed_zero_known_state);
    RUN_TEST(pcg_bounded_representative_value);
    RUN_TEST(pcg_bounded_one_always_zero);
    RUN_TEST(pcg_bounded_zero_throws_no_draw);
    RUN_TEST(pcg_save_load_exact_continuation);
    RUN_TEST(pcg_map_transition_does_not_perturb_canonical);
    RUN_TEST(pcg_presentation_rng_does_not_perturb_canonical);
    RUN_TEST(pcg_npc_movement_uses_canonical_rng);
    RUN_TEST(pcg_npc_save_load_canonical_continuation);
    RUN_TEST(random_chance_correct_probability_contract);
    RUN_TEST(random_chance_invalid_percent_throws);
    RUN_TEST(no_second_authoritative_rng_stream);
    RUN_TEST(pcg_dv_draw_count_two_semantic);
    RUN_TEST(pcg_v4_migration_deterministic);
    RUN_TEST(pcg_v5_save_roundtrip);
    RUN_TEST(behavior_sdefer_routes_to_scheduler);
    RUN_TEST(behavior_known_unimplemented_errors_explicitly);
    RUN_TEST(behavior_unknown_unregistered_errors_explicitly);
    RUN_TEST(behavior_writes_script_var_errors_before_branch);
    // sem_special_still_rejected_after_registry_cleanup -> migrated to legality_gate_test.cpp
    RUN_TEST(compat_exact_hash_gives_exacthash_match);
    RUN_TEST(compat_modified_hash_layout_valid_not_rejected);
    RUN_TEST(compat_incompatible_profile_fails_explicitly);
    RUN_TEST(species_finder_stock_count_is_251);
    RUN_TEST(species_finder_bulbasaur_record_correct);
    RUN_TEST(species_finder_last_record_is_mew);
    RUN_TEST(species_finder_non251_profile_same_path);
    RUN_TEST(species_linker_refs_are_exact_resolved);
    RUN_TEST(species_linker_unknown_species_invalid_domain);
    RUN_TEST(daycare_species_252_save_load_accepted);
    RUN_TEST(species_icon_map_covers_full_domain);
    RUN_TEST(event_script_id_canonical_format_npc);
    RUN_TEST(event_script_id_canonical_format_bg);
    RUN_TEST(event_script_id_canonical_format_coord);
    RUN_TEST(event_script_id_missing_fails_explicitly);
    RUN_TEST(event_script_id_no_local_positional_survives);
    RUN_TEST(vm_result_zero_takes_false_branch);
    RUN_TEST(vm_result_one_takes_true_branch);
    RUN_TEST(vm_result_nonzero_integer_true);
    RUN_TEST(vm_setvar_from_result_zero_stores_zero);
    RUN_TEST(vm_call_returns_to_continuation);
    RUN_TEST(vm_nested_calls_unwind_correctly);
    RUN_TEST(vm_callee_end_does_not_exit_top_level);
    RUN_TEST(vm_endall_inside_nested_call_terminates);
    RUN_TEST(vm_sdefer_cleared_on_rebind);
    RUN_TEST(vm_sdefer_cleared_on_loop_destroy);
    RUN_TEST(vm_deferred_failure_propagates_error);
    RUN_TEST(capability_show_hide_npc_updates_npc_state);
    RUN_TEST(capability_face_actor_updates_npc_facing);
    RUN_TEST(capability_face_actor_player_updates_player_facing);
    RUN_TEST(capability_face_player_updates_npc_facing_toward_player);
    RUN_TEST(capability_teleport_npc_updates_npc_position);
    RUN_TEST(capability_set_last_talked_records_id);
    RUN_TEST(capability_set_scene_persists_in_game_state);
    RUN_TEST(capability_state_var_persists_in_game_state);

    std::cout << "\n=== Results ===\n";
    std::cout << std::dec << "Passed: " << g_tests_passed << "\n";
    std::cout << "Failed: " << g_tests_failed << "\n";
    return g_tests_failed > 0 ? 1 : 0;
}

