// runtime_test_engine_main.cpp
// Main for runtime_test_engine — engine-only TUs (no compiler IR variants).
// TUs: runtime_test_core, _maps, _blast_radius, _integration, _warp_semantics, _rtc
// Run: runtime_test_engine <rom_path>
#include "engine/world/collision.hpp"
#include "crystal/rom/loader.hpp"
#include "crystal/rom/profile.hpp"
#include <iostream>
#include <string>
#include "scripting/runtime_test_shared.hpp"

int  g_tests_passed      = 0;
int  g_tests_failed      = 0;
bool g_current_test_failed = false;
const crystal::RomData*           g_rom     = nullptr;
const crystal::ExtractionProfile* g_profile = nullptr;
std::string g_generated_lua;

void run_test(const char* name, void (*test)()) {
    std::cout << "Running " << name << "... ";
    g_current_test_failed = false;
    try { test();
        if (g_current_test_failed) { std::cout << "FAIL\n"; g_tests_failed++; }
        else { std::cout << "PASS\n"; g_tests_passed++; }
    } catch (const std::exception& e) {
        std::cout << "EXCEPTION: " << e.what() << "\n"; g_tests_failed++;
    }
}

// Forward declarations
void test_async_movement_batched_table();
void test_async_movement_completion_callback();
void test_async_movement_fast_forward();
void test_async_movement_final_position();
void test_async_movement_lua_yields();
void test_async_movement_manager_basic();
void test_async_movement_not_instant();
void test_async_movement_position_not_jumped();
void test_async_movement_progresses_over_ticks();
void test_async_movement_resumes_after_complete();
void test_async_movement_with_turns();
void test_bg_event_hidden_item_collected_blocked();
void test_bg_event_hidden_item_uncollected_triggers();
void test_bg_event_ifnotset_set_blocked();
void test_bg_event_ifnotset_unset_triggers();
void test_bg_event_ifset_ifnotset_condition_flag_integration();
void test_bg_event_ifset_set_triggers();
void test_bg_event_ifset_unset_blocked();
void test_bg_event_type_package_roundtrip_all_types();
void test_charmap_contractions();
void test_charmap_pokemon_text();
void test_coins_account_does_not_alias_player_money();
void test_coins_has_money_reads_coins_not_player_money();
void test_coins_save_load_independent_of_player_money();
void test_collision_blocked_bounds();
void test_collision_blocked_entity();
void test_collision_blocked_wall();
void test_collision_class_semantic_queries();
void test_collision_classifier_adversarial_misclassified_ids();
void test_collision_classifier_source_proven_constants();
void test_collision_dimension_uses_collision_not_tile_width();
void test_collision_entity_target_blocks();
void test_collision_ledge_detection();
void test_collision_passable_floor();
void test_collision_semantic_boundary_adversarial();
void test_collision_side_wall_blocks();
void test_connection_landing_math();
void test_connection_newbark_to_route29();
void test_connection_semantic_azalea_west_to_route34();
void test_connection_semantic_cherrygrove_north_to_route30();
void test_connection_semantic_route26_west_to_route27();
void test_connection_semantic_route27_east_to_route26();
void test_connection_strip_after_strip_rejected();
void test_connection_strip_before_strip_rejected();
void test_connection_strip_first_valid_coordinate();
void test_connection_strip_last_valid_coordinate();
void test_create_pokemon_missing_species_throws();
void test_create_pokemon_registered_species_succeeds();
void test_crystal_npc_visibility_flag_set_means_hidden();
void test_decode_newbarktownsign();
void test_directional_ledge_semantic_preservation();
void test_door_auto_step_routes_through_movement_manager();
void test_duplicate_physical_binding_release();
void test_elms_lab_has_exit_warp();
void test_f2_movement_order_right_down_down();
void test_f2_movement_order_right_right_up();
void test_f3_player_authority_step_syncs_gamestate();
void test_flag_gamestate_set_clear_check_roundtrip();
void test_flag_identity_hex_canonical();
void test_flag_map_condition_matches_script_set();
void test_flag_namespace_event_engine_distinct();
void test_gamestate_flags_persist();
void test_gamestate_rng_persist();
void test_gamestate_serialize_insertion_order_determinism();
void test_gamestate_serialize_roundtrip();
void test_gamestate_variables_persist();
void test_gamestate_warp_memory_persist();
void test_get_player_pos_authoritative();
void test_headless_loop_facing_update();
void test_headless_loop_input_locked_during_movement();
void test_headless_loop_movement_blocked();
void test_headless_loop_movement_ticks();
void test_headless_loop_spawn_player();
void test_headless_newbark_determinism();
void test_headless_newbark_script_execution();
void test_headless_newbark_sign_interaction();
void test_headless_newbark_teacher_interaction();
void test_headless_newbark_walk_one_tile();
void test_hide_npc_no_flag_is_transient();
void test_interaction_bg_event_facing_requirement();
void test_interaction_bg_event_found();
void test_interaction_bounds_check();
void test_interaction_counter_extends_reach();
void test_interaction_counter_tile_detection();
void test_interaction_directional_bg_wrong_facing();
void test_interaction_facing_calculation();
void test_interaction_moving_npc_not_interactable();
void test_interaction_object_found();
void test_interaction_object_priority_over_bg();
void test_load_map_owns_copy_prevents_dangling();
void test_lua_flags_vars_persist_through_gamestate_save_load();
void test_lua_flags_without_gamestate_uses_stubs_only();
void test_lua_goto_works();
void test_lua_load_script_directory_deterministic_order();
void test_lua_runtime_creates();
void test_lua_runtime_ctx_exists();
void test_lua_runtime_executes_script_yields_on_wait_button();
void test_lua_runtime_executes_simple();
void test_lua_runtime_full_pipeline();
void test_lua_runtime_loads_generated_script();
void test_lua_runtime_multiple_scripts();
void test_lua_runtime_wait_frames();
void test_lua_syntax_error_throws_explicitly();
void test_map_scene_per_map_persistent();
void test_movement_combined_steps_and_turns();
void test_movement_face_changes_facing();
void test_movement_lua_emit_steps();
void test_movement_lua_emit_turn();
void test_movement_parse_commands();
void test_movement_parse_with_turn();
void test_movement_player_movement();
void test_movement_world_state_changes();
void test_newbark_has_connections();
void test_newbark_has_warps();
void test_newbarktown_bg_event_positions();
void test_newbarktown_collision_movement_blocked();
void test_newbarktown_door_tiles();
void test_newbarktown_entity_collision();
void test_newbarktown_interaction_determinism();
void test_newbarktown_known_blocked_tiles();
void test_newbarktown_known_walkable_tiles();
void test_newbarktown_no_rom_addresses_in_scripts();
void test_newbarktown_object_positions();
void test_newbarktown_object_priority_integration();
void test_newbarktown_package_roundtrip_interaction();
void test_newbarktown_real_collision_map();
void test_newbarktown_sign_correct_facing();
void test_newbarktown_sign_wrong_facing();
void test_newbarktown_teacher_decode();
void test_newbarktown_teacher_default_branch();
void test_newbarktown_teacher_first_branch();
void test_newbarktown_teacher_interaction();
void test_newbarktown_teacher_lua_emit();
void test_newbarktown_teacher_second_branch();
void test_newbarktown_teacher_third_branch();
void test_newbarktown_water_tiles();
void test_no_gamestate_flags_fallback_to_stubs();
void test_npc_can_traverse_side_wall_from_allowed_direction();
void test_npc_cannot_cross_side_wall_from_forbidden_direction();
void test_npc_restore_after_production_transition();
void test_npc_restore_fresh_map_keeps_rom_defaults();
void test_npc_restore_in_production_setup();
void test_npc_restore_no_snapshot_keeps_rom_defaults_after_transition();
void test_npc_restore_save_load_full_round_trip();
void test_pcstorage_deposit_moves_pokemon_exactly_once();
void test_player_destination_reserved_against_npc();
void test_player_money_does_not_alias_coins();
void test_pokemon_move_slots_initialized_to_defaults();
void test_prepare_for_save_snapshots_npc_state();
void test_production_bootstrap_script_mutates_gamestate();
void test_rtc_dst_disable_twice_idempotent();
void test_rtc_dst_enable_set_clock_disable_net_reversal();
void test_rtc_dst_enable_twice_idempotent();
void test_rtc_fake_clock_advance();
void test_rtc_hour_minute_from_offset();
void test_rtc_midnight_daily_rollover();
void test_rtc_negative_offset();
void test_rtc_period_boundaries();
void test_rtc_save_load_preserves_offset();
void test_rtc_set_clock_recomputes_offset();
void test_rtc_set_daylight_saving_adjusts_offset();
void test_rtc_ticks_do_not_advance_rtc();
void test_rtc_weekday_derivation();
void test_save_mutate_load_identical();
void test_script_yielded_locks_input();
void test_scripted_coordinate_warp_uses_explicit_coords();
void test_set_scene_check_scene_per_map_isolation();
void test_set_scene_per_map_affects_only_current_map();
void test_set_scene_per_map_save_load_preserves_both();
void test_show_hide_npc_persists_to_gamestate_flags();
void test_special_tileset_fixed_palette_extracted();
void test_sprite_id_mapping_authoritative();
void test_tileset_id_bounds_0_1_36_37();
void test_typechart_dual_type_immunity_remains_zero();
void test_typechart_dual_type_out_of_range_throws();
void test_typechart_explicit_values_survive_lookup();
void test_typechart_immunity_is_zero_not_unset();
void test_typechart_max_valid_index_accepted();
void test_typechart_out_of_range_get_throws();
void test_typechart_out_of_range_set_throws();
void test_warp_elms_lab_to_newbark_last_map();
void test_warp_invalid_index_out_of_range_fails();
void test_warp_invalid_index_zero_fails();
void test_warp_newbark_to_elms_lab();
void test_warp_target_map_no_warps_fails();
void test_warp_to_spawn_no_fn_errors_explicitly();
void test_warp_to_spawn_uses_gamestate_backup_warp();
void test_warp_valid_index_succeeds();
void test_world_manager_get_warp_at();
void test_world_manager_load_map();
void test_write_state_var_stores_result();

int main(int argc, char* argv[]) {
    if (argc < 2) { std::cerr << "Usage: " << argv[0] << " <rom_path>\n"; return 1; }
    auto rom = crystal::RomData::load(argv[1]);
    if (!rom) { std::cerr << "Failed to load ROM\n"; return 1; }
    auto& registry = crystal::ProfileRegistry::instance();
    auto profile = registry.get_profile_by_hash(rom->hash());
    if (!profile) { std::cerr << "ROM not supported\n"; return 1; }
    g_rom = rom.get(); g_profile = profile;
    std::cout << "\n=== Runtime Tests (engine) ===\n\n";

    RUN_TEST(lua_runtime_creates);
    RUN_TEST(lua_runtime_executes_simple);
    RUN_TEST(lua_runtime_ctx_exists);
    RUN_TEST(decode_newbarktownsign);
    RUN_TEST(lua_runtime_loads_generated_script);
    RUN_TEST(lua_runtime_executes_script_yields_on_wait_button);
    RUN_TEST(lua_runtime_full_pipeline);
    RUN_TEST(lua_runtime_multiple_scripts);
    RUN_TEST(lua_runtime_wait_frames);
    RUN_TEST(lua_goto_works);
    RUN_TEST(newbarktown_teacher_decode);
    RUN_TEST(newbarktown_teacher_lua_emit);
    RUN_TEST(newbarktown_teacher_default_branch);
    RUN_TEST(newbarktown_teacher_first_branch);
    RUN_TEST(newbarktown_teacher_second_branch);
    RUN_TEST(newbarktown_teacher_third_branch);
    RUN_TEST(charmap_pokemon_text);
    RUN_TEST(charmap_contractions);
    RUN_TEST(movement_parse_commands);
    RUN_TEST(movement_parse_with_turn);
    RUN_TEST(movement_lua_emit_steps);
    RUN_TEST(movement_lua_emit_turn);
    RUN_TEST(f2_movement_order_right_down_down);
    RUN_TEST(f2_movement_order_right_right_up);
    RUN_TEST(movement_world_state_changes);
    RUN_TEST(movement_face_changes_facing);
    RUN_TEST(movement_combined_steps_and_turns);
    RUN_TEST(movement_player_movement);
    RUN_TEST(async_movement_manager_basic);
    RUN_TEST(async_movement_not_instant);
    RUN_TEST(async_movement_progresses_over_ticks);
    RUN_TEST(async_movement_final_position);
    RUN_TEST(async_movement_with_turns);
    RUN_TEST(async_movement_fast_forward);
    RUN_TEST(async_movement_completion_callback);
    RUN_TEST(async_movement_batched_table);
    RUN_TEST(async_movement_lua_yields);
    RUN_TEST(async_movement_position_not_jumped);
    RUN_TEST(async_movement_resumes_after_complete);
    RUN_TEST(collision_class_semantic_queries);
    RUN_TEST(collision_passable_floor);
    RUN_TEST(collision_blocked_wall);
    RUN_TEST(collision_blocked_bounds);
    RUN_TEST(collision_blocked_entity);
    RUN_TEST(collision_entity_target_blocks);
    RUN_TEST(collision_side_wall_blocks);
    RUN_TEST(collision_ledge_detection);
    RUN_TEST(collision_semantic_boundary_adversarial);
    RUN_TEST(interaction_facing_calculation);
    RUN_TEST(interaction_counter_tile_detection);
    RUN_TEST(interaction_bg_event_facing_requirement);
    RUN_TEST(interaction_object_found);
    RUN_TEST(interaction_bg_event_found);
    RUN_TEST(interaction_object_priority_over_bg);
    RUN_TEST(interaction_moving_npc_not_interactable);
    RUN_TEST(interaction_directional_bg_wrong_facing);
    RUN_TEST(interaction_counter_extends_reach);
    RUN_TEST(interaction_bounds_check);
    RUN_TEST(newbarktown_real_collision_map);
    RUN_TEST(newbarktown_known_walkable_tiles);
    RUN_TEST(newbarktown_known_blocked_tiles);
    RUN_TEST(newbarktown_water_tiles);
    RUN_TEST(newbarktown_door_tiles);
    RUN_TEST(newbarktown_collision_movement_blocked);
    RUN_TEST(newbarktown_entity_collision);
    RUN_TEST(newbarktown_bg_event_positions);
    RUN_TEST(newbarktown_object_positions);
    RUN_TEST(newbarktown_sign_wrong_facing);
    RUN_TEST(newbarktown_sign_correct_facing);
    RUN_TEST(newbarktown_teacher_interaction);
    RUN_TEST(newbarktown_object_priority_integration);
    RUN_TEST(newbarktown_package_roundtrip_interaction);
    RUN_TEST(bg_event_type_package_roundtrip_all_types);
    RUN_TEST(bg_event_ifset_ifnotset_condition_flag_integration);
    RUN_TEST(newbarktown_no_rom_addresses_in_scripts);
    RUN_TEST(newbarktown_interaction_determinism);
    RUN_TEST(headless_loop_spawn_player);
    RUN_TEST(headless_loop_facing_update);
    RUN_TEST(headless_loop_movement_blocked);
    RUN_TEST(headless_loop_movement_ticks);
    RUN_TEST(headless_loop_input_locked_during_movement);
    RUN_TEST(headless_newbark_walk_one_tile);
    RUN_TEST(headless_newbark_sign_interaction);
    RUN_TEST(headless_newbark_teacher_interaction);
    RUN_TEST(headless_newbark_determinism);
    RUN_TEST(headless_newbark_script_execution);
    RUN_TEST(newbark_has_warps);
    RUN_TEST(newbark_has_connections);
    RUN_TEST(elms_lab_has_exit_warp);
    RUN_TEST(world_manager_load_map);
    RUN_TEST(world_manager_get_warp_at);
    RUN_TEST(warp_newbark_to_elms_lab);
    RUN_TEST(warp_elms_lab_to_newbark_last_map);
    RUN_TEST(collision_dimension_uses_collision_not_tile_width);
    RUN_TEST(warp_invalid_index_zero_fails);
    RUN_TEST(warp_invalid_index_out_of_range_fails);
    RUN_TEST(warp_target_map_no_warps_fails);
    RUN_TEST(warp_valid_index_succeeds);
    RUN_TEST(load_map_owns_copy_prevents_dangling);
    RUN_TEST(typechart_immunity_is_zero_not_unset);
    RUN_TEST(typechart_dual_type_immunity_remains_zero);
    RUN_TEST(typechart_explicit_values_survive_lookup);
    RUN_TEST(create_pokemon_missing_species_throws);
    RUN_TEST(create_pokemon_registered_species_succeeds);
    RUN_TEST(typechart_out_of_range_get_throws);
    RUN_TEST(typechart_out_of_range_set_throws);
    RUN_TEST(typechart_max_valid_index_accepted);
    RUN_TEST(typechart_dual_type_out_of_range_throws);
    RUN_TEST(lua_load_script_directory_deterministic_order);
    RUN_TEST(pcstorage_deposit_moves_pokemon_exactly_once);
    RUN_TEST(pokemon_move_slots_initialized_to_defaults);
    RUN_TEST(connection_strip_first_valid_coordinate);
    RUN_TEST(connection_strip_last_valid_coordinate);
    RUN_TEST(connection_strip_before_strip_rejected);
    RUN_TEST(connection_strip_after_strip_rejected);
    RUN_TEST(player_destination_reserved_against_npc);
    RUN_TEST(npc_cannot_cross_side_wall_from_forbidden_direction);
    RUN_TEST(npc_can_traverse_side_wall_from_allowed_direction);
    RUN_TEST(connection_newbark_to_route29);
    RUN_TEST(connection_landing_math);
    RUN_TEST(connection_semantic_cherrygrove_north_to_route30);
    RUN_TEST(connection_semantic_azalea_west_to_route34);
    RUN_TEST(connection_semantic_route26_west_to_route27);
    RUN_TEST(connection_semantic_route27_east_to_route26);
    RUN_TEST(gamestate_serialize_roundtrip);
    RUN_TEST(gamestate_flags_persist);
    RUN_TEST(gamestate_variables_persist);
    RUN_TEST(lua_flags_vars_persist_through_gamestate_save_load);
    RUN_TEST(lua_flags_without_gamestate_uses_stubs_only);
    RUN_TEST(gamestate_warp_memory_persist);
    RUN_TEST(gamestate_rng_persist);
    RUN_TEST(save_mutate_load_identical);
    RUN_TEST(gamestate_serialize_insertion_order_determinism);
    RUN_TEST(f3_player_authority_step_syncs_gamestate);
    RUN_TEST(rtc_hour_minute_from_offset);
    RUN_TEST(rtc_fake_clock_advance);
    RUN_TEST(rtc_set_clock_recomputes_offset);
    RUN_TEST(rtc_period_boundaries);
    RUN_TEST(rtc_weekday_derivation);
    RUN_TEST(rtc_midnight_daily_rollover);
    RUN_TEST(rtc_negative_offset);
    RUN_TEST(rtc_ticks_do_not_advance_rtc);
    RUN_TEST(rtc_save_load_preserves_offset);
    RUN_TEST(rtc_set_daylight_saving_adjusts_offset);
    RUN_TEST(rtc_dst_enable_twice_idempotent);
    RUN_TEST(rtc_dst_disable_twice_idempotent);
    RUN_TEST(rtc_dst_enable_set_clock_disable_net_reversal);
    RUN_TEST(scripted_coordinate_warp_uses_explicit_coords);
    RUN_TEST(warp_to_spawn_uses_gamestate_backup_warp);
    RUN_TEST(warp_to_spawn_no_fn_errors_explicitly);
    RUN_TEST(door_auto_step_routes_through_movement_manager);
    RUN_TEST(crystal_npc_visibility_flag_set_means_hidden);
    RUN_TEST(show_hide_npc_persists_to_gamestate_flags);
    RUN_TEST(hide_npc_no_flag_is_transient);
    RUN_TEST(write_state_var_stores_result);
    RUN_TEST(map_scene_per_map_persistent);
    RUN_TEST(get_player_pos_authoritative);
    RUN_TEST(flag_namespace_event_engine_distinct);
    RUN_TEST(prepare_for_save_snapshots_npc_state);
    RUN_TEST(npc_restore_in_production_setup);
    RUN_TEST(npc_restore_fresh_map_keeps_rom_defaults);
    RUN_TEST(npc_restore_save_load_full_round_trip);
    RUN_TEST(set_scene_check_scene_per_map_isolation);
    RUN_TEST(set_scene_per_map_affects_only_current_map);
    RUN_TEST(set_scene_per_map_save_load_preserves_both);
    RUN_TEST(npc_restore_after_production_transition);
    RUN_TEST(npc_restore_no_snapshot_keeps_rom_defaults_after_transition);
    RUN_TEST(coins_account_does_not_alias_player_money);
    RUN_TEST(player_money_does_not_alias_coins);
    RUN_TEST(coins_has_money_reads_coins_not_player_money);
    RUN_TEST(coins_save_load_independent_of_player_money);
    RUN_TEST(production_bootstrap_script_mutates_gamestate);
    RUN_TEST(no_gamestate_flags_fallback_to_stubs);
    RUN_TEST(lua_syntax_error_throws_explicitly);
    RUN_TEST(flag_identity_hex_canonical);
    RUN_TEST(flag_gamestate_set_clear_check_roundtrip);
    RUN_TEST(flag_map_condition_matches_script_set);
    RUN_TEST(collision_classifier_adversarial_misclassified_ids);
    RUN_TEST(collision_classifier_source_proven_constants);
    RUN_TEST(script_yielded_locks_input);
    RUN_TEST(tileset_id_bounds_0_1_36_37);
    RUN_TEST(duplicate_physical_binding_release);
    RUN_TEST(special_tileset_fixed_palette_extracted);
    RUN_TEST(bg_event_ifset_unset_blocked);
    RUN_TEST(bg_event_ifset_set_triggers);
    RUN_TEST(bg_event_ifnotset_unset_triggers);
    RUN_TEST(bg_event_ifnotset_set_blocked);
    RUN_TEST(bg_event_hidden_item_uncollected_triggers);
    RUN_TEST(bg_event_hidden_item_collected_blocked);
    RUN_TEST(sprite_id_mapping_authoritative);
    RUN_TEST(directional_ledge_semantic_preservation);

    std::cout << "\n=== Results ===\n";
    std::cout << std::dec << "Passed: " << g_tests_passed << "\n";
    std::cout << "Failed: " << g_tests_failed << "\n";
    return g_tests_failed > 0 ? 1 : 0;
}

