#!/usr/bin/env bash
# regen_fixtures.sh
# Verify or regenerate all binary fixtures from .asm sources using pinned RGBDS.
#
# RGBDS version: 1.0.3  (must match the provenance in README.md)
# Run from the Enginemon workspace root.
#
# NOTE: This script is run MANUALLY before committing changes to .asm files.
# Normal CI uses the checked-in .bin files directly — RGBDS is NOT required
# at test time.
#
# Modes:
#   --verify  (default) Assemble each fixture and compare to checked-in .bin.
#                       Exits nonzero if any mismatch is found.
#   --update            Assemble each fixture and OVERWRITE the checked-in .bin.
#                       Updating fixtures must be intentional.  Never implicit.
#
# Usage (verify mode — default):
#   ./tests/oracle/tools/regen_fixtures.sh
#   ./tests/oracle/tools/regen_fixtures.sh --verify
#
# Usage (update mode — intentional overwrite):
#   ./tests/oracle/tools/regen_fixtures.sh --update

set -e

ORACLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FIXTURES_DIR="$ORACLE_DIR/fixtures"
TMP_DIR="$(mktemp -d)"
RGBASM="${RGBASM:-rgbasm}"
RGBLINK="${RGBLINK:-rgblink}"
EXPECTED_VER="1.0.3"
MODE="verify"

# Parse arguments
for arg in "$@"; do
    case "$arg" in
        --verify) MODE="verify" ;;
        --update) MODE="update" ;;
        *)
            echo "Usage: $0 [--verify | --update]"
            exit 1
            ;;
    esac
done

# ─── Version check ──────────────────────────────────────────────────────────
if ! command -v "$RGBASM" &>/dev/null; then
    echo "ERROR: rgbasm not found on PATH."
    echo "Install RGBDS $EXPECTED_VER and add it to PATH, or set RGBASM=/path/to/rgbasm."
    exit 1
fi

RGBDS_VER=$("$RGBASM" --version 2>&1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
if [ "$RGBDS_VER" != "$EXPECTED_VER" ]; then
    echo "ERROR: RGBDS version $RGBDS_VER found, expected $EXPECTED_VER."
    echo "Pin RGBDS to $EXPECTED_VER to ensure byte-identical fixture output."
    echo "Refusing to proceed with unpinned version."
    exit 1
fi

echo "RGBDS $RGBDS_VER confirmed."
echo "Mode: $MODE"
echo ""

# ─── Fixture assembly helper ─────────────────────────────────────────────────
# assemble_fixture <name>
# Assembles fixtures/<name>.asm → tmp/<name>.bin
# In verify mode: diffs against fixtures/<name>.bin and exits 1 on mismatch.
# In update mode: copies generated bytes over fixtures/<name>.bin.
MISMATCHES=0

assemble_fixture() {
    local name="$1"
    local asm_file="$FIXTURES_DIR/${name}.asm"
    local bin_file="$FIXTURES_DIR/${name}.bin"
    local obj_file="$TMP_DIR/${name}.o"
    local gen_file="$TMP_DIR/${name}.bin"

    if [ ! -f "$asm_file" ]; then
        echo "SKIP: $asm_file not found"
        return
    fi

    # Assemble
    if ! "$RGBASM" -o "$obj_file" "$asm_file" 2>/dev/null; then
        echo "FAIL (assemble): $name"
        MISMATCHES=$((MISMATCHES + 1))
        return
    fi

    # Link to flat binary (-x = raw, no ROM header/padding)
    if ! "$RGBLINK" -o "$gen_file" -x "$obj_file" 2>/dev/null; then
        echo "FAIL (link): $name"
        MISMATCHES=$((MISMATCHES + 1))
        return
    fi

    if [ "$MODE" = "verify" ]; then
        if diff -q "$bin_file" "$gen_file" >/dev/null 2>&1; then
            # Show hex for confirmation
            hex=$(od -A n -t x1 "$gen_file" | tr -s ' ' | tr -d '\n' | sed 's/^ //')
            printf "OK    %s  (%d bytes)  %s\n" "$name" "$(wc -c < "$gen_file")" "$hex"
        else
            echo "MISMATCH: $name"
            echo "  checked-in: $(od -A n -t x1 "$bin_file" | tr -s ' ' | tr -d '\n')"
            echo "  generated:  $(od -A n -t x1 "$gen_file" | tr -s ' ' | tr -d '\n')"
            MISMATCHES=$((MISMATCHES + 1))
        fi
    else
        # Update mode
        cp "$gen_file" "$bin_file"
        hex=$(od -A n -t x1 "$gen_file" | tr -s ' ' | tr -d '\n' | sed 's/^ //')
        printf "UPDATED %s  (%d bytes)  %s\n" "$name" "$(wc -c < "$gen_file")" "$hex"
    fi
}

# ─── Phase 1 fixtures ────────────────────────────────────────────────────────
assemble_fixture "event_operand_order"
assemble_fixture "event_flag_vs_engine_flag"
assemble_fixture "text_tx_ram_mixed"
assemble_fixture "text_tx_decimal"
assemble_fixture "movement_step_dig"
assemble_fixture "movement_skyfall_top"
assemble_fixture "sdefer_bank_resolution"

# Phase 1.5 connection fixture
assemble_fixture "connection_offset_direction"

# ─── Phase 2 fixtures ────────────────────────────────────────────────────────
assemble_fixture "event_zero_and_one_byte_ops"
assemble_fixture "event_word_operand_ops"
assemble_fixture "event_multi_byte_ops"
assemble_fixture "event_pointer_and_branch_ops"
assemble_fixture "movement_directional_family"
assemble_fixture "movement_parameterized_family"
assemble_fixture "movement_non_directional_misc"
assemble_fixture "text_tx_box_and_bcd"
assemble_fixture "text_tx_stringbuffer_and_far"
assemble_fixture "text_literal_overlap_opcodes"

# ─── Result ──────────────────────────────────────────────────────────────────
rm -rf "$TMP_DIR"
echo ""
if [ "$MISMATCHES" -gt 0 ]; then
    echo "RESULT: $MISMATCHES mismatch(es) found. Fixtures do NOT match RGBDS $EXPECTED_VER output."
    echo "  To update: run with --update"
    exit 1
else
    if [ "$MODE" = "verify" ]; then
        echo "RESULT: All fixtures byte-identical to RGBDS $EXPECTED_VER output."
    else
        echo "RESULT: All fixtures updated."
    fi
    exit 0
fi
