// crystal/script/lua_emitter.cpp
// Emits Lua code from Script IR

#include "crystal/script/lua_emitter.hpp"
#include <sstream>
#include <fstream>
#include <filesystem>
#include <set>

namespace crystal {

LuaEmitter::LuaEmitter(EmitterConfig config) : config_(config) {}

void LuaEmitter::emit_indent(std::ostream& out) {
    for (int i = 0; i < current_indent_ * config_.indent_width; ++i) {
        out << ' ';
    }
}

void LuaEmitter::emit_line(std::ostream& out, const std::string& line) {
    emit_indent(out);
    out << line << "\n";
}

void LuaEmitter::emit_comment(std::ostream& out, const std::string& comment) {
    emit_indent(out);
    out << "-- " << comment << "\n";
}

std::string LuaEmitter::escape_string(const std::string& s) {
    std::string result;
    result.reserve(s.size() + 10);
    for (char c : s) {
        switch (c) {
            case '\n': result += "\\n"; break;
            case '\r': result += "\\r"; break;
            case '\t': result += "\\t"; break;
            case '"': result += "\\\""; break;
            case '\\': result += "\\\\"; break;
            default: result += c; break;
        }
    }
    return result;
}

std::string LuaEmitter::make_label_function_name(const LabelRef& ref) {
    std::string name = ref.name;
    for (char& c : name) {
        if (!isalnum(c) && c != '_') {
            c = '_';
        }
    }
    if (!name.empty() && isdigit(name[0])) {
        name = "_" + name;
    }
    return name;
}

void LuaEmitter::emit_header(std::ostream& out, const ScriptIR& script) {
    out << "-- Script: " << script.name << "\n";
    if (config_.emit_address_comments) {
        out << "-- ROM: 0x" << std::hex << script.rom_start << std::dec << "\n";
    }
    out << "-- Generated by Enginemon Crystal Frontend\n";
    out << "\n";
    out << "local script = {}\n\n";
}

void LuaEmitter::emit_footer(std::ostream& out, const ScriptIR& script) {
    out << "\nreturn script\n";
}

std::string LuaEmitter::emit(const ScriptIR& script) {
    std::ostringstream out;
    emit(script, out);
    return out.str();
}

// Collect all jump targets to know which addresses need labels
static std::set<uint32_t> collect_jump_targets(const ScriptIR& script) {
    std::set<uint32_t> targets;
    for (const auto& inst : script.instructions) {
        std::visit([&targets](const auto& op) {
            using T = std::decay_t<decltype(op)>;
            if constexpr (std::is_same_v<T, Op_Jump>) {
                targets.insert(op.target.rom_address);
            } else if constexpr (std::is_same_v<T, Op_JumpIf>) {
                targets.insert(op.target.rom_address);
            }
        }, inst.op);
    }
    return targets;
}

void LuaEmitter::emit(const ScriptIR& script, std::ostream& out) {
    state_.script = &script;
    state_.address_to_label.clear();
    current_indent_ = 0;
    
    // Collect all jump targets
    auto jump_targets = collect_jump_targets(script);
    
    // Build address -> label mapping
    for (const auto& inst : script.instructions) {
        if (jump_targets.count(inst.rom_address)) {
            std::ostringstream label;
            label << "label_" << std::hex << inst.rom_address;
            state_.address_to_label[inst.rom_address] = label.str();
        }
    }
    
    // Check if we have any jump targets (which means labels after returns)
    bool needs_end_label = !state_.address_to_label.empty();
    
    emit_header(out, script);
    
    // Main function
    out << "function script.main(ctx)\n";
    current_indent_ = 1;
    
    // Initialize result variable that check operations use
    emit_line(out, "local result = false");
    emit_line(out, "");
    
    for (const auto& inst : script.instructions) {
        // Emit label if this address is a jump target
        auto label_it = state_.address_to_label.find(inst.rom_address);
        if (label_it != state_.address_to_label.end()) {
            emit_line(out, "::" + label_it->second + "::");
        }
        
        // For End operations when we have labels, emit goto to end instead of return
        // (because return can't be followed by anything including labels)
        bool is_end = std::holds_alternative<Op_End>(inst.op);
        if (is_end && needs_end_label) {
            emit_line(out, "goto script_end");
        } else {
            emit_instruction(out, inst);
        }
    }
    
    // Add end label if needed
    if (needs_end_label) {
        emit_line(out, "::script_end::");
    }
    
    current_indent_ = 0;
    out << "end\n";
    
    emit_footer(out, script);
}

void LuaEmitter::emit_instruction(std::ostream& out, const Instruction& inst) {
    if (config_.emit_address_comments) {
        std::ostringstream comment;
        comment << "0x" << std::hex << inst.rom_address;
        emit_comment(out, comment.str());
    }
    
    std::visit([this, &out](const auto& op) { emit_op(out, op); }, inst.op);
}

void LuaEmitter::emit_op(std::ostream& out, const Op_End& op) {
    emit_line(out, "return");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_SetFlag& op) {
    emit_line(out, "ctx.flags:set(" + std::to_string(op.flag) + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_ClearFlag& op) {
    emit_line(out, "ctx.flags:clear(" + std::to_string(op.flag) + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_CheckFlag& op) {
    // Store result in the shared 'result' variable for subsequent iftrue/iffalse
    emit_line(out, "result = ctx.flags:check(" + std::to_string(op.flag) + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_OpenText& op) {
    emit_line(out, "ctx.ui:open_text()");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_CloseText& op) {
    emit_line(out, "ctx.ui:close_text()");
}

// Emit a semantic TextSequence as Lua code
// The runtime receives text_sequence() with a table of operations
void LuaEmitter::emit_text_sequence(std::ostream& out, const TextSequence& seq) {
    // Build a Lua table representing the text sequence
    // Format: { {op="text", text="..."}, {op="line"}, {op="para"}, ... }
    std::ostringstream table;
    table << "{";
    bool first = true;
    
    for (const auto& elem : seq.elements) {
        if (!first) table << ", ";
        first = false;
        
        switch (elem.op) {
            case TextOp::Text:
                table << "{op=\"text\", text=\"" << escape_string(elem.text) << "\"}";
                break;
            case TextOp::Line:
                table << "{op=\"line\"}";
                break;
            case TextOp::Next:
                table << "{op=\"next\"}";
                break;
            case TextOp::Para:
                table << "{op=\"para\"}";
                break;
            case TextOp::Cont:
                table << "{op=\"cont\"}";
                break;
            case TextOp::Scroll:
                table << "{op=\"scroll\"}";
                break;
            case TextOp::Done:
                table << "{op=\"done\"}";
                break;
            case TextOp::Prompt:
                table << "{op=\"prompt\"}";
                break;
            
            // Dynamic text commands - emit with their parameters
            // Runtime handles substitution of actual values
            case TextOp::TextRam:
                // Display RAM contents (address is semantic reference)
                table << "{op=\"ram\", addr=" << elem.addr << "}";
                break;
            case TextOp::TextBcd:
                // Display BCD number
                table << "{op=\"bcd\", addr=" << elem.addr << ", flags=" << (int)elem.param1 << "}";
                break;
            case TextOp::TextMove:
                // Move cursor position
                table << "{op=\"move\", pos=" << elem.addr << "}";
                break;
            case TextOp::TextBox:
                // Draw text box
                table << "{op=\"box\", addr=" << elem.addr << ", w=" << (int)elem.param1 << ", h=" << (int)elem.param2 << "}";
                break;
            case TextOp::TextLow:
                // Move to bottom of screen
                table << "{op=\"low\"}";
                break;
            case TextOp::TextPromptButton:
                // Wait for button press
                table << "{op=\"waitbutton\"}";
                break;
            case TextOp::TextScroll:
                // Scroll text up
                table << "{op=\"txscroll\"}";
                break;
            case TextOp::TextAsm:
                // Inline assembly - terminates text, runtime handles
                table << "{op=\"asm\"}";
                break;
            case TextOp::TextDecimal:
                // Display decimal number
                table << "{op=\"decimal\", addr=" << elem.addr << ", param=" << (int)elem.param1 << "}";
                break;
            case TextOp::TextPause:
                // Brief pause
                table << "{op=\"pause\"}";
                break;
            case TextOp::TextStringBuffer:
                // Display string buffer contents
                table << "{op=\"buffer\", id=" << (int)elem.param1 << "}";
                break;
            case TextOp::TextDay:
                // Display current day
                table << "{op=\"day\"}";
                break;
            case TextOp::TextFar:
                // Far text pointer - runtime resolves
                table << "{op=\"far\", addr=" << elem.addr << ", bank=" << (int)elem.param2 << "}";
                break;
            case TextOp::TextSoundItem:
                // Play item jingle
                table << "{op=\"snd_item\"}";
                break;
            case TextOp::TextSoundCaught:
                // Play caught mon jingle
                table << "{op=\"snd_caught\"}";
                break;
            case TextOp::TextSoundFanfare:
                // Play fanfare
                table << "{op=\"snd_fanfare\"}";
                break;
            case TextOp::TextRaw:
                // Raw bytes - for debugging/round-trip only
                table << "{op=\"raw\"}";
                break;
        }
    }
    table << "}";
    
    emit_line(out, "ctx.ui:text_sequence(" + table.str() + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_Text& op) {
    emit_text_sequence(out, op.sequence);
}

void LuaEmitter::emit_op(std::ostream& out, const Op_JumpText& op) {
    // jumptext is a compound: opentext + writetext + waitbutton + closetext + end
    emit_comment(out, "jumptext - shows text and ends");
    emit_line(out, "ctx.ui:open_text()");
    emit_text_sequence(out, op.sequence);
    emit_line(out, "coroutine.yield(\"wait_button\")");
    emit_line(out, "ctx.ui:close_text()");
    emit_line(out, "return");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_JumpTextFacePlayer& op) {
    // jumptextfaceplayer = faceplayer + jumptext
    emit_comment(out, "jumptextfaceplayer - faces player, shows text, ends");
    emit_line(out, "ctx.world:face_player()");
    emit_line(out, "ctx.ui:open_text()");
    emit_text_sequence(out, op.sequence);
    emit_line(out, "coroutine.yield(\"wait_button\")");
    emit_line(out, "ctx.ui:close_text()");
    emit_line(out, "return");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_JumpStd& op) {
    emit_line(out, "ctx.std:" + op.name + "()");
    emit_line(out, "return");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_CallStd& op) {
    emit_line(out, "ctx.std:" + op.name + "()");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_YesNo& op) {
    // yesorno sets result to true (YES) or false (NO)
    emit_line(out, "result = ctx.ui:yes_no()");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_GiveItem& op) {
    std::ostringstream line;
    line << "ctx.inventory:give(" << op.item << ", " << (int)op.count << ")";
    emit_line(out, line.str());
}

void LuaEmitter::emit_op(std::ostream& out, const Op_GivePokemon& op) {
    std::ostringstream line;
    line << "ctx.party:add_pokemon(" << op.species << ", " << (int)op.level << ")";
    emit_line(out, line.str());
}

void LuaEmitter::emit_op(std::ostream& out, const Op_Warp& op) {
    std::ostringstream line;
    line << "ctx.world:warp(" << op.map << ", " << (int)op.x << ", " << (int)op.y << ")";
    emit_line(out, line.str());
}

void LuaEmitter::emit_op(std::ostream& out, const Op_WildBattle& op) {
    std::ostringstream line;
    line << "local result = ctx.battle:start_wild(" << op.species 
         << ", " << (int)op.level << ")";
    emit_line(out, line.str());
}

void LuaEmitter::emit_op(std::ostream& out, const Op_TrainerBattle& op) {
    emit_line(out, "local result = ctx.battle:start_trainer(" + 
              std::to_string(op.trainer) + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_PlayMusic& op) {
    emit_line(out, "ctx.audio:play_music(" + std::to_string(op.music) + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_Special& op) {
    emit_line(out, "ctx.special:" + op.name + "()");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_Raw& op) {
    emit_comment(out, "RAW: opcode 0x" + std::to_string(op.opcode) + " " + op.comment);
}

// Control flow with proper goto labels
void LuaEmitter::emit_op(std::ostream& out, const Op_Jump& op) {
    auto it = state_.address_to_label.find(op.target.rom_address);
    if (it != state_.address_to_label.end()) {
        emit_line(out, "goto " + it->second);
    } else {
        emit_comment(out, "jump to " + op.target.name + " (target not in script)");
    }
}

void LuaEmitter::emit_op(std::ostream& out, const Op_JumpIf& op) {
    auto it = state_.address_to_label.find(op.target.rom_address);
    if (it != state_.address_to_label.end()) {
        // Determine condition based on Op_JumpIf.condition
        // condition is "true", "false", "== N", "!= N", "> N", "< N"
        std::string cond;
        if (op.condition == "true") {
            cond = "result";
        } else if (op.condition == "false") {
            cond = "not result";
        } else {
            // Comparison conditions like "== 5", "!= 3"
            cond = "result " + op.condition;
        }
        emit_line(out, "if " + cond + " then goto " + it->second + " end");
    } else {
        emit_comment(out, "conditional jump to " + op.target.name + " (target not in script)");
    }
}

void LuaEmitter::emit_op(std::ostream& out, const Op_Call& op) {
    // Calls to subroutines - would need separate function generation
    emit_comment(out, "scall " + op.target.name + " (subroutine not inlined)");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_Return& op) {
    emit_line(out, "return");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_SetVar& op) {
    emit_line(out, "ctx.flags:set_var(" + std::to_string(op.var) + ", " + 
              std::to_string(op.value) + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_AddVar& op) {
    emit_line(out, "ctx.flags:add_var(" + std::to_string(op.var) + ", " + 
              std::to_string(op.delta) + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_CheckVar& op) {
    // Store comparison result in 'result' for subsequent conditionals
    emit_line(out, "result = ctx.flags:get_var(" + std::to_string(op.var) + 
              ") " + op.op + " " + std::to_string(op.value));
}

void LuaEmitter::emit_op(std::ostream& out, const Op_Choice& op) {
    emit_line(out, "result = ctx.ui:choice({})");  // TODO: options
}

void LuaEmitter::emit_op(std::ostream& out, const Op_TakeItem& op) {
    emit_line(out, "ctx.inventory:take(" + std::to_string(op.item) + ", " + 
              std::to_string(op.count) + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_CheckItem& op) {
    emit_line(out, "result = ctx.inventory:has(" + std::to_string(op.item) + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_GiveMoney& op) {
    emit_line(out, "ctx.inventory:give_money(" + std::to_string(op.amount) + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_TakeMoney& op) {
    emit_line(out, "ctx.inventory:take_money(" + std::to_string(op.amount) + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_CheckMoney& op) {
    emit_line(out, "result = ctx.inventory:has_money(" + std::to_string(op.amount) + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_HealParty& op) {
    emit_line(out, "ctx.party:heal_all()");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_CheckPartyCount& op) {
    emit_line(out, "result = ctx.party:count()");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_CheckPartySpecies& op) {
    emit_line(out, "result = ctx.party:has_species(" + std::to_string(op.species) + ")");
}

// Helper to convert Direction enum to Lua string
static std::string direction_to_string(Direction dir) {
    switch (dir) {
        case Direction::Down: return "down";
        case Direction::Up: return "up";
        case Direction::Left: return "left";
        case Direction::Right: return "right";
        default: return "down";
    }
}

void LuaEmitter::emit_op(std::ostream& out, const Op_ApplyMovement& op) {
    emit_comment(out, "applymovement " + std::to_string(op.object_id));
    
    // Emit movement commands in exact source order.
    //
    // ORDERING CONTRACT: Crystal movement sequences are ordered programs, not
    // direction bags.  RIGHT, DOWN, DOWN must execute as RIGHT then DOWN then DOWN.
    // We emit one ctx.world:move_actor() call per step, preserving source order.
    //
    // Adjacent identical steps are each emitted separately so that the runtime
    // executes them one tile at a time with correct collision/warp checks at
    // each intermediate cell.
    
    for (const auto& cmd : op.commands) {
        if (cmd.type == MovementType::StepEnd) {
            break;
        }
        
        // Step commands — emit one call per step in source order
        if (cmd.is_step()) {
            std::string dir = direction_to_string(cmd.direction);
            emit_line(out, "ctx.world:move_actor(" + std::to_string(op.object_id) +
                      ", \"" + dir + "\", 1)");
        }
        // Turn commands — face without moving
        else if (cmd.is_turn()) {
            emit_line(out, "ctx.world:face_actor(" + std::to_string(op.object_id) +
                      ", \"" + direction_to_string(cmd.direction) + "\")");
        }
        // Sleep/wait commands
        else if (cmd.type == MovementType::StepSleep && cmd.param > 0) {
            emit_line(out, "ctx.util:wait_frames(" + std::to_string(cmd.param) + ")");
        }
        // Other non-step commands (hide, remove, special animations) — skip emit for now
    }
    
    // Yield until movement completes
    emit_line(out, "coroutine.yield(\"movement\")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_FacePlayer& op) {
    if (op.object_id == 0) {
        emit_line(out, "ctx.world:face_player()");
    } else {
        emit_line(out, "ctx.world:face_player(" + std::to_string(op.object_id) + ")");
    }
}

void LuaEmitter::emit_op(std::ostream& out, const Op_FaceObject& op) {
    emit_line(out, "ctx.world:face_object(" + std::to_string(op.object_id) + ", \"down\")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_ShowSprite& op) {
    emit_line(out, "ctx.world:show_npc(" + std::to_string(op.object_id) + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_HideSprite& op) {
    emit_line(out, "ctx.world:hide_npc(" + std::to_string(op.object_id) + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_WarpToSpawn& op) {
    emit_line(out, "ctx.world:warp_to_spawn()");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_CheckBattleResult& op) {
    emit_line(out, "result = ctx.battle:last_result()");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_PlaySfx& op) {
    emit_line(out, "ctx.audio:play_sfx(" + std::to_string(op.sfx) + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_PlayCry& op) {
    emit_line(out, "ctx.audio:play_cry(" + std::to_string(op.species) + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_WaitSfx& op) {
    emit_line(out, "ctx.audio:wait_sfx()");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_StopMusic& op) {
    emit_line(out, "ctx.audio:stop_music()");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_FadeOut& op) {
    emit_line(out, "ctx.ui:fade_out(" + std::to_string(op.speed) + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_FadeIn& op) {
    emit_line(out, "ctx.ui:fade_in(" + std::to_string(op.speed) + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_ShowMapName& op) {
    emit_line(out, "ctx.ui:show_map_name()");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_Earthquake& op) {
    emit_line(out, "ctx.ui:earthquake(" + std::to_string(op.intensity) + ")");
}

void LuaEmitter::emit_op(std::ostream& out, const Op_CheckTime& op) {
    emit_line(out, "result = ctx.time:is_morning()");  // Simplified
}

void LuaEmitter::emit_op(std::ostream& out, const Op_CheckDay& op) {
    emit_line(out, "result = ctx.time:day_of_week() == 0");  // Simplified
}

void LuaEmitter::emit_op(std::ostream& out, const Op_Wait& op) {
    if (op.frames > 0) {
        emit_line(out, "ctx.util:wait_frames(" + std::to_string(op.frames) + ")");
    }
}

void LuaEmitter::emit_op(std::ostream& out, const Op_WaitButton& op) {
    emit_line(out, "coroutine.yield(\"wait_button\")");
}

void LuaEmitter::emit_all(const ScriptIRSet& scripts, const std::filesystem::path& dir) {
    std::filesystem::create_directories(dir);
    
    for (const auto& script : scripts.scripts) {
        std::filesystem::path path = dir / (script.name + ".lua");
        std::ofstream out(path);
        if (out) {
            emit(script, out);
        }
    }
}

} // namespace crystal
